### ISSUE TITLE
ft - main sections + columns

### ISSUE THREAD

**Issue by kevinkoos** [cs361fall2017/team13#13]
Implement css to style the general layout and main game section. 2 days.

**Comment by mgray35** [comment]
I don't remember who did this but hasn't this been completed?

**Comment by kevinkoos** [comment]
Sprint 3 update: Lets add some styling to the columns so that they fill up the area they are in and look a bit better.

**Comment by osugraytr** [comment]
made code easier to read, now waiting for a pull request to get accepted
