### ISSUE TITLE
ft - deck and discard pile

### ISSUE THREAD

**Issue by kevinkoos** [cs361fall2017/team13#14]
Implement html and css for the deck and discard piles. 1 day

**Comment by mgray35** [comment]
Since no one has claimed any of these as far as I'm aware, I'll try to tackle this one

**Comment by mgray35** [comment]
Deck and discard pile still need work but should be good now as far ass html and css goes

**Comment by kevinkoos** [comment]
js already implemented, that was part of the merge conflict
