### ISSUE TITLE
ft - js functionality

### ISSUE THREAD

**Issue by kevinkoos** [cs361fall2017/team13#15]
Implement the functionality for the deck pile, click to remove, move buttons, score, and bottom bar readout. 1-2 days
deck, remove, move, and bottom bar functionality are dependent on their completion.

**Comment by mgray35** [comment]
You said you wanted to work on this one, right @kevinkoos ?

**Comment by kevinkoos** [comment]
Yea, I need to learn jQuery soon so this seems to be a nice opportunity.

**Comment by kevinkoos** [comment]
click to remove #20 , deck pile # #21 , move buttons will be added next sprint(depending on what the sprint is), and score/readout are up in the air as to whether they'll be done or not.
