### ISSUE TITLE
ft - move buttons

### ISSUE THREAD

**Issue by kevinkoos** [cs361fall2017/team13#16]
css and html for move buttons implemented. 1 day

**Comment by thadenf** [comment]
are the 5 remaining issues still open?

**Comment by kevinkoos** [comment]
they're all still open

**Comment by osugraytr** [comment]
Can we close this issue? I cannot currently look at the code

**Comment by kevinkoos** [comment]
This issue is still open, right now for this all we need is 4 dummy buttons in the column area. I don't know enough jQuery to get them running right now so we can just put the text box move segment outside of the main area so we can test moving cards.
