### ISSUE TITLE
ft - set up html

### ISSUE THREAD

**Issue by kevinkoos** [cs361fall2017/team13#18]
The html for the game is pretty bare and needs to be sectioned off properly so everyone can work on the css and html of the separate parts. 1 day 
This needs to be done before any of the other html and css is started.

**Comment by osugraytr** [comment]
I'm not sure if I have the knowledge to do this. What do you mean by splinting it up? like the headers and stuff like that?

**Comment by kevinkoos** [comment]
We need an html structure to put everything on so we can easily style them through css. We won't need to mess with headers as they'll be generated automatically. We need to group elements (some may need to be added but only placeholders) together in a way that makes sense based off of our ui prototype.

**Comment by mgray35** [comment]
My HTML experience is pretty limited but I can take a look at it

**Comment by kevinkoos** [comment]
For the most part we just need some <div>'s and classes/id for the various elements. e.g. deck/discard area would be a <div> with another 2 <div>'s inside for the deck and discard individually with the deal button inside the deck <div>

**Comment by osugraytr** [comment]
I'll work on it and comment the code here

**Comment by kevinkoos** [comment]
If you're going to do it just push the branch and make a pull request when you're done, we can comment on it there.

**Comment by kevinkoos** [comment]
#19
