### ISSUE TITLE
ft - move on ace only

### ISSUE THREAD

**Issue by kevinkoos** [cs361fall2017/team13#28]
Modify the move function in Game.java (comment out the pre-existing code) to only move when the card to move is an Ace.  <1 day

**Comment by mgray35** [comment]
I went ahead and implemented this, but I'm not sure what you mean by "comment out the pre-existing code." Isn't this just adding another condition to the move function?

**Comment by kevinkoos** [comment]
Yea I don't know what I was thinking, I think I thought it was a switch statement or something

**Comment by mgray35** [comment]
Finished this yesterday; just closing the issue now
