### ISSUE TITLE
bug - SpanishDeck constructor

### ISSUE THREAD

**Issue by kevinkoos** [cs361fall2017/team13#61]
Due to the way java's inheritance works, a sub-class object will always call the superclass's constructor. Both Deck and SpanishDeck will need to be refactored to where they both call `buildDeck()`, just like in the original code. 1 day.

**Comment by mgray35** [comment]
The way Java constructors and inheritance works confuses me. Would this work?:
`public Deck() {
        this.buildDeck();
        this.shuffle();
    }`
and
`public SpanishDeck() {
        this.buildDeck();
        this.shuffle();
    }`
where `buildDeck()` is private and defined differently in each class.

**Comment by kevinkoos** [comment]
That should work, although I believe since `SpanishDeck()` calls its superclass's constructor, `this.buildDeck()` and `this.shuffle()` would have already been called. Since you've already added most of the code for the Spanish cards, change `game.deckType` in the js console to `S` and reset. That was how I found this bug.

**Comment by mgray35** [comment]
Okay I figured it out. Should be fixed in the latest commit of #60.

**Comment by mgray35** [comment]
Fixed in #60
